<?php /** @var Magento\Framework\View\TemplateEngine\Php $this */ ?>
<div>
    <div class="full-action-name" style="background-color: <?php echo $this->getData('background_color') ?>;
        margin: 10px;
        padding: 30px;
        border: #d3d3d3 2px dotted;
        border-radius: 20px;
        text-align: center;
        ">
        <h2><?php echo __('Here will be full action name') ?></h2>
    </div>
</div>


<script type="text/x-magento-init">
    {
        "*": {
            "fullActionName": {
                "container": ".full-action-name > h2",
                "fan": "<?php echo $block->getFullActionName(); ?>"

            }
        }
    }

</script>